### ISSUE TITLE
Benchmark plot change request from Stratospheric Working Group

### ISSUE THREAD

**Issue by lizziel** [geoschem/gcpy#11]
Susan Strahan, Co-Chair of GEOS-Chem Stratospheric Working Group writes:
"Dylan, Seb, and I are happy with those plots EXCEPT they’ve got to be in log-pressure and run from about 100 to 1 hPa. So this is the only change to benchmarks we are recommending at this time. Only the plots made for the stratosphere need to change."

**Comment by yantosca** [comment]
I have just pushed updates so that the stratospheric zonal mean plots will use a log-pressure Y-axis, see sample below. 

![zonalmean](https://user-images.githubusercontent.com/5880296/62961698-41b67c80-bdcb-11e9-82fd-c75468612532.png)

NOTE: All plot windows will use the same Y-axes, the example here just shows the first two.
