### ISSUE TITLE
[FEATURE REQUEST] Flexible end day in benchmark scripts

### ISSUE THREAD

**Issue by lizziel** [geoschem/gcpy#115]
Our 1-month benchmark run script can be programmed to run for any month or year. However, it is fixed to start on 1st day of the month and end on 1st day of the next month. Sometimes I want to do a shorter run, such as one day or one week, and generate the same comparison as our 1-month benchmark. This does not work due to the hard-coded day 1 and 1-month assumption.

This is not an urgent request but something to put on the wish list. I could implement it later on. The interface would be the same as now but also allow specifying (1) start day and (2) simulation duration.

**Comment by yantosca** [comment]
I think this is something that we could easily integrate with a YAML configuration file, such as is proposed in #117.

**Comment by yantosca** [comment]
I think this is something that we could easily integrate with a YAML configuration file, such as is proposed in #117.

**Comment by lizziel** [comment]
Pinging @laestrada who volunteered to work on this. This feature will be useful for automatic benchmarking of 1-hr runs on AWS cloud.

**Comment by laestrada** [comment]
Hi @lizziel, 
I think I have a solution just about working (have tested it for 1Hr and 1Mon comparison plots), but I am unclear on what the expected behavior should be with flexible dates when running with `is_legacy: True`. Specifically in [this code block](https://github.com/geoschem/gcpy/blob/92799047f4475a974cee07e496817983bfe688d4/benchmark/run_1mo_benchmark.py#L307) for monthlys the start datetime is set to `20XX-XX-16T12:00:00`. What would be the expected behavior for shorter or longer time periods? eg. if I am using a run with `start_date: 2019-07-01T00:00:00` and `end_date: 2019-07-01T01:00:00` would this be averaged to a start date of `2019-07-01T00:30:00`?

**Comment by laestrada** [comment]
This feature was merged in with PR #140
