### ISSUE TITLE
[FEATURE REQUEST] Move gcpy/benchmark.py to the benchmark/ folder

### ISSUE THREAD

**Issue by yantosca** [geoschem/gcpy#245]
## Add your feature request below:

Right now we have many of the benchmarking driver routines in the `gcpy/benchmark.py` folder.  But perhaps this should be moved to the `gcpy/benchmark/` folder so that we can centralize all benchmarking routines in a single place.

**Comment by lizziel** [comment]
I think all the source code in a python package is supposed to be in a subfolder of the same name of the package. That is why we have most of the python files in `gcpy/gcpy`. Our `gcpy/benchmark` folder is a bit odd, and I think it was separated out just to contain scripts that are used externally from the package. To conform to standard python package structure we should probably be moving towards having a `gcpy/gcpy/benchmark` folder rather than moving source to `gcpy/benchmark`.

There is information on how to structure a python packages [here](https://py-pkgs.org/04-package-structure.html). It looks like `gcpy/src/gcpy` would be even better than `gcpy/gcpy`.

**Comment by yantosca** [comment]
Thanks Lizzie.  I'll look into doing this.

**Comment by yantosca** [comment]
We can now close this issue as #250 has been merged into the GCPy 1.4.0 development stream.
