### ISSUE TITLE
[DISCUSSION] To-do list for distributing GCPy as a package

### ISSUE THREAD

**Issue by yantosca** [geoschem/gcpy#29]
We will need to do the following before we can ship GCPy as a Python package:

1. Implement semantic versioning (i.e. version numbers X.Y.Z)
2. Make sure all *.py files are PEP-8 compliant by running pycodestyle on them
3. Add more examples & scripts -- solicit input from community
4. Expand the existing unit tests, and implement continuous integration on TravisCI
5. Add documentation on readthedocs -- right now we need to get ownership of that back from D. Rothenberg.
6. Push gcpy to conda or pip

Any others?

**Comment by lizziel** [comment]
I think we can make gcpy as a package available before/during #3. Accepting input from the community will be rolling. 

Regarding #5, we already have ownership of gcpy on readthedocs. The issue is that the implementation is such that all dependencies are loaded which results in running out of memory. Ideally we would re-implement to skip that loading step.

**Comment by yantosca** [comment]
GCPy is now shipped via conda-forge as geoschem-gcpy.  Therefore I believe we can close this out.
