### ISSUE TITLE
Changing y axis on gcpy.compare_zonal_mean

### ISSUE THREAD

**Issue by jmoch1214** [geoschem/gcpy#3]
For the gcpy.compare_zonal_mean the y axis is hPa, which ends up being an issue if you want to look at stratospheric changes and also gives you a distorted view of the troposphere. Is there a way to change the y-axis to log(pressure) or to km? That would give a better vertical profile where thing's are so compressed for the upper troposphere and above.

**Comment by lizziel** [comment]
The function is implemented to only plot hPa since this is the unit used for benchmarking. There are no plans to expand this to other units, or log-scale, unless the GEOS-Chem benchmarking changes. You can specify the pressure range to see only the strat. See gcpy/benchmark/run_1mo_benchmark.py for an example of how we show strat in benchmark plots.

If you want to expand the functionality you could copy the function to a new file and adapt it to do what you want. I recommend forking the repository and customizing your own version. You can then feed back your changes via a pull request.
