### ISSUE TITLE
[FEATURE] Improved automatic colorbar scientific notation

### ISSUE THREAD

**Issue by lizziel** [geoschem/gcpy#64]
It's pretty difficult to make the colorbar always automatically choose the best notation for tick values. Way back I added what I thought was an okay enough algorithm for gcpy to not show colorbar values with so many decimal places the text ran together. Looking at recent plots generated with gcpy 0.2.0 (dev) I think it could be improved.

Here is an example where scientific notation is used when maybe it shouldn't be:
<img width="380" alt="Screen Shot 2020-03-17 at 12 55 27 PM" src="https://user-images.githubusercontent.com/651947/76881765-02b04400-6850-11ea-9087-95280faaef2f.png">

It seems silly to have label bounds around -0.001e2 and 0.0005e2. Why not -0.1 and 0.05? Maybe the code to auto-label could be played with a bit more to capture this case.

**Comment by lizziel** [comment]
Separate issue, but I have to comment on it. Negative concentrations?

**Comment by WilliamDowns** [comment]
In this plot, +1e2 is a base value and the colormap describes the offset of values from that base. The majority of plotted values in the above image are actually between 99.9990 and 99.9995 (-.0010 + 1e2 and -.0005 + 1e2). This is an automatic feature in Matplotlib when all plotted values are within a small range. Since this functionality is confusing to look at and not well-explained, it has been removed from GCPy plots. Colorbar ticks for colormaps across small value ranges now show true values rather than offsets.

![ColorbarTickFixExample](https://user-images.githubusercontent.com/22124674/78057361-9a378b80-7354-11ea-8dc9-e89c5aaf1a10.png)
